[tool.poetry]
name = "rlenv"
version = "0.2.6"
description = "A strongly typed Reinforcement Learning framework"
authors = ["Yannick Molinghen <yannick.molinghen@ulb.be>"]
license = "MIT"
readme = "readme.md"

[tool.poetry.dependencies]
python = ">=3.10,<3.11"
numpy = "^1.23.4"
tqdm = "^4.64.1"
smac = {git = "https://github.com/oxwhirl/smac.git"}
gymnasium = {extras = ["atari"], version = "^0.28.1"}
opencv-python = "^4.6.0.66"
pettingzoo = "^1.22.3"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
