[tool.poetry]
name = "rlenv"
version = "0.3.1"
description = "A strongly typed Reinforcement Learning framework"
authors = ["Yannick Molinghen <yannick.molinghen@ulb.be>"]
license = "MIT"
readme = "readme.md"

[tool.poetry.dependencies]
python = ">=3.10"
numpy = ">=1.23.4"
opencv-python = ">=4.6.0.66"

smac = { git = "https://github.com/oxwhirl/smac.git", optional = true }
gymnasium = { extras = [
    "atari",
    "accept-rom-license",
], version = "^0.28.1", optional = true }
pettingzoo = { version = "^1.22.3", optional = true }


[tool.ruff]
line-length = 140

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"


# pytest configuration
[tool.pytest.ini_options]
testpaths = ["tests"]
pythonpath = "src"
