[project]
name = "marl-env"
version = "2.0.0"
description = "A strongly typed Multi-Agent Reinforcement Learning framework"
authors = [{ name = "Yannick Molinghen", email = "yannick.molinghen@ulb.be" }]
readme = "readme.md"

dependencies = ["numpy>=1.23", "opencv-python>=4.6.0", "pytest", "pytest-xdist"]


[project.optional-dependencies]
smac = [
    "swig",
    "smac@git+https://github.com/oxwhirl/smac.git",
    "pysc2@git+https://github.com/google-deepmind/pysc2.git", # Required to fix a bug in pysc2
    "pygame==2.5.2",
    "pymunk==6.6.0",
]
gymnasium = ["gymnasium"]
pettingzoo = ["pettingzoo"]


[tool.ruff]
line-length = 140

[build-system]
requires = ["setuptools>=61.0", "build", "pip"]
build-backend = "setuptools.build_meta"

# pytest configuration
[tool.pytest.ini_options]
filterwarnings = [
    # Ignore deprecation warnings related to Pysc2 (smac)
    "ignore:Call to deprecated create function Descriptor().*:DeprecationWarning",
    "ignore:Call to deprecated create function FieldDescriptor().*:DeprecationWarning",
    "ignore:Call to deprecated create function EnumValueDescriptor().*:DeprecationWarning",
    "ignore:Call to deprecated create function EnumDescriptor().*:DeprecationWarning",
    "ignore:Call to deprecated create function FileDescriptor().*:DeprecationWarning",
    "ignore:pkg_resources is deprecated as an API*:DeprecationWarning",
    "ignore:protobuf",
]
# Run tests on two cores with xdist
addopts = "-n 4"
testpaths = ["tests"]
pythonpath = "src"
