name: Build & Test

on:
  push:
    branches:
      - main
      - master
      - dev
    tags:
      - '*'
  pull_request:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  test:
    name: Test
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - windows-latest
          - macOS-latest
        target:
          - x86_64
          - aarch64
        python-version: 
          - '3.10'
          - '3.11'
          - '3.12' # Dependency ale-py does not yet support Python 3.12
        exclude:
          - os: windows-latest
            target: 'aarch64'

    runs-on: ${{ matrix.os }}
    steps:
      # Checkout the repository
      - name: Checkout
        uses: actions/checkout@v4
      # Setup poetry and run Python tests
      - name: Python setup
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies and run pytest
        run: |
          pip install poetry
          poetry update
          poetry run pytest -n 4

  build:
    name: Build package 📦
    if: startsWith(github.ref, 'refs/tags/')  # only publish to PyPI on tag pushes
    needs: test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.10"
    - name: Install UV
      uses: yezz123/setup-uv@v4
    - name: Build wheels
      run: |
        uv pip install pip build
        uv run python -m build
    
    - name: Upload package distributions 📡
      uses: actions/upload-artifact@v3
      with:
        name: wheels
        path: dist/


  publish-to-pypi:
    name: Publish Python 🐍 distribution 📦 to PyPI
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: pypi
      url: https://pypi.org/p/marl-env 
    permissions:
      id-token: write  # IMPORTANT: this permission is mandatory for trusted publishing
    steps:
    - name: Download all the dists
      uses: actions/download-artifact@v3
      with:
        name: wheels
        path: dist/
    - name: Publish distribution 📦 to PyPI
      uses: pypa/gh-action-pypi-publish@release/v1
