name: Build & Test

on:
  push:
    branches:
      - main
      - master
      - dev
    tags:
      - '*'
  pull_request:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  test:
    name: Build & Test
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - windows-latest
          - macOS-latest
        target:
          - x86_64
          - aarch64
        python-version: 
          - '3.10'
          - '3.11'
          - '3.12' # Dependency ale-py does not yet support Python 3.12
        exclude:
          - os: windows-latest
            target: 'aarch64'

    runs-on: ${{ matrix.os }}
    steps:
      # Checkout the repository
      - name: Checkout
        uses: actions/checkout@v4
      - name: Python setup
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          
      - name: Install UV and create venv
        run: |
          pip install uv
          uv venv .venv

      - name: Activate virtual environment (Windows)
        if: ${{ runner.os == 'Windows' }}
        run: |
          "VIRTUAL_ENV=.venv" | Out-File -FilePath $env:GITHUB_ENV -Append
          "$PWD/.venv/Scripts" | Out-File -FilePath $env:GITHUB_PATH -Append
      - name: Activate virtual environment (Unix)
        if: ${{ runner.os != 'Windows' }}
        run: |
          echo "VIRTUAL_ENV=.venv" >> $GITHUB_ENV
          echo "$PWD/.venv/bin" >> $GITHUB_PATH

      - name: Install dependencies
        # From here on, the virtual environment is active
        run: |
          uv pip install -r pyproject.toml --extra pettingzoo gymnasium
      - name: Pytest
        run: pytest -n 4

  build:
    if: ${{ github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master' }}
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - windows-latest
          - macOS-latest
        target:
          - x86_64
          - aarch64
        python-version: 
          - '3.10'
          - '3.11'
          - '3.12'
        exclude:
          - os: windows-latest
            target: 'aarch64'

    runs-on: ${{ matrix.os }}
    needs: [test]
    steps:
      - uses: actions/checkout@v3
      - name: Python setup
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install UV and create the virtualenv
        run: |
          pip install uv
          uv venv .venv

      - name: Activate virtual environment (Windows)
        if: ${{ runner.os == 'Windows' }}
        run: |
          "VIRTUAL_ENV=.venv" | Out-File -FilePath $env:GITHUB_ENV -Append
          "$PWD/.venv/Scripts" | Out-File -FilePath $env:GITHUB_PATH -Append
      - name: Activate virtual environment (Unix)
        if: ${{ runner.os != 'Windows' }}
        run: |
          echo "VIRTUAL_ENV=.venv" >> $GITHUB_ENV
          echo "$PWD/.venv/bin" >> $GITHUB_PATH
          
      - name: Install dependencies
        run: |
          uv pip install -r pyproject.toml
          uv pip install build pip
      - name: Build wheels
        run: python -m build --wheel --outdir dist .
      - name: Upload wheels
        uses: actions/upload-artifact@v4
        with:
          name: wheels-${{ runner.os }}-${{ matrix.target }}-${{ matrix.python-version }}
          path: dist

  release:
    name: Release
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: wheels*
          path: dist
      - name: Publish to PyPI
        uses: PyO3/maturin-action@v1
        env:
          MATURIN_PYPI_TOKEN: ${{ secrets.PYPI_API_TOKEN }}
        with:
          command: upload
          args: --skip-existing *

