name: Build & Test

on:
  push:
    branches:
      - main
      - master
      - dev
    tags:
      - '*'
  pull_request:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  test:
    name: Build & Test
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - windows-latest
          - macOS-latest
        target:
          - x86_64
          - aarch64
        python-version: 
          - '3.10'
          - '3.11'
          - '3.12' # Dependency ale-py does not yet support Python 3.12
        exclude:
          - os: windows-latest
            target: 'aarch64'

    runs-on: ${{ matrix.os }}
    steps:
      # Checkout the repository
      - name: Checkout
        uses: actions/checkout@v4
      # Setup poetry and run Python tests
      - name: Python setup
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies and run pytest
        run: |
          pip install poetry
          poetry update
          poetry run pytest -n 4

  build-publish:
    if: ${{ github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master' }}
    runs-on: ubuntu-latest
    needs: [test]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Python setup
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Build and publish to pypi
        uses: JRubics/poetry-publish@v2.0
        with:
          pypi_token: ${{ secrets.PYPI_TOKEN }}


